### ISSUE TITLE
Spec: Define behavior when invalid ParticipantStatus is returned from participant methods

### ISSUE THREAD

**Issue by xstefank** [eclipse/microprofile-lra#143]
As we currently have as per Participant State Model two separate paths for LRA execution success - Complete and error - Compensate we have a duplicated states for every possible outcome depending on whether LRA is closing or cancelling. But this statuses are returned by end users so the specification should probably guard against potential errors. Consider for instance examples:

https://gist.github.com/xstefank/79a346f0ae988895684790d5a4d6db94

or something more probable:

https://gist.github.com/xstefank/6dc7ab62511a51a2cbecdcaaedd73ad3

My concern is that these situations should be handled in unified way so not that one implementation throws exception and other secretly transform state to its correct variant. Another option would be to model ParticipantStatus with only one state model (Finished, Finishing, FailedToFinish or similar).

**Comment by mmusgrov** [comment]
There is already a note about this in the spec and it is also covered in the state model but the decision made at this morning's hangout is to add more text.

But note that the spec does cover the situation and it says the situation MUST be logged. Also note that we cannot write a TCK test for this since there is no API for obtaining the final status of compensators and LRAs. Each implementation should have their own private test to validate that the final states are correct (so in the first gist example the final state of the LRA which was asked to close would be `FailedToClose`)

**Comment by xstefank** [comment]
I will add some text that just describes that invalid outcome must be logged and that it maps to FailedTo* states.
