### ISSUE TITLE
SPEC: Indicate automatic time out is only for Active LRA.

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-lra#231]
The main parts around the time out functionality in the spec

>The business logic may wish to control how long an LRA should remain active
for before it becomes eligible for automatic cancellation by providing values
for the `timeLimit` and `timeUnit` element of the `@LRA` annotation.

But imagine following scenario
- LRA starts with timeout of 1 sec
- Participant A joins LRA with end=false
- Participant B joins LRA with end=true
- @Complete callbacks of Participant A and B are called.
- Participant A @Complete replies with `Compensating`
- Participant B @Complete replies with `Compensated`

- Participant A @Complete should be called again to get final outcome

But before this second call to Participant A @Complete is performed, the timeout is reached and thus LRA should be cancelled?

Main problem here is that Participant B is not even aware of the LRA anymore since it can forget about the LRA besides the fact that Participant A and B could first receive event Complete and later on Compensate.

So best is to explicitly define that only an Active LRA can be automatically cancelled.

**Comment by xstefank** [comment]
Isn't "The business logic may wish to control how long an LRA should remain active" stating that timeout is ignored when the LRA is no longer active? Which is the case in your example, because when participant B uses end = true, LRA transitions from Active state to one of the Completing or Canceling states. However, if you think this needs to be formulated differently I am not opposed :)

**Comment by rdebusscher** [comment]
Yeah maybe this is slight play in words, you are correct @xstefank.

In my head I have a difference between Active state and _active_ (not having a final state)

**Comment by xstefank** [comment]
In any case, I see no harm in clarifying this more if there might be any kind of possible misinterpretation.

**Comment by mmusgrov** [comment]
> But before this second call to Participant A @complete is performed, the timeout is reached and thus LRA should be cancelled?

The LRA protocol is designed to guarantee atomic outcomes - therefore if the decision is to close the LRA all participants are told to complete (none will ever be asked to compensate). And vice versa if the LRA is cancelled (due to a timeout or otherwise).

In the outlined scenario:

> Participant A @complete replies with Compensating

This would imply that A did the wrong thing and moves to the state `FailedToComplete`. The only legal call after this is to be told to Forget about the LRA.

> So best is to explicitly define that only an Active LRA can be automatically cancelled.

"When the time limit is reached the LRA is cancelled". The only valid transition (according to the state model) to the Cancelled state is from the Active state. Therefore it is implicit that cancelling an LRA can only happen if it is already `Active`.

> Main problem here is that Participant B is not even aware of the LRA anymore since it can forget about the LRA besides the fact that Participant A and B could first receive event Complete and later on Compensate.

So it is not a problem since B did the correct thing.
Also, receiving both events would be illegal - a participant can never received Complete and later on Compensate since that would break the "all" part of the "all or nothing" (atomicity) guarantee.

**Comment by rdebusscher** [comment]
Yes, my example has an error, it should be

>Participant A @complete replies with Completing

anyway, we are on the same page.

>The LRA protocol is designed to guarantee atomic outcomes - therefore if the decision is to close the LRA all participants are told to complete (none will ever be asked to compensate). 

So that was the reason for to explicitly mention `LRA with Status Active`.

Since for me an active LRA is not the same as an LRA with status Active.

But since I'm the only one and probably most people read the spec text correct, I'm closing this one.
